---
apiVersion: v1
kind: Service
metadata:
  name: python-service
  labels:
    name: python-service
    app: dfp-app
spec:
  ports:
  - port: 80
    targetPort: 80
  selector:
      name: python-pod
      app: dfp-app
