--Descobrindo resultado das empresas 
WITH DRE AS (

SELECT 

	DISTINCT 
	ORDEM_EXERC,
	DT_INI_EXERC,
	DT_FIM_EXERC,
	DT_REFER,
	CNPJ_CIA, 
	DENOM_CIA, 
	DS_CONTA, 
	VL_CONTA 
FROM [B3_DATA_DISCOVERING].[dbo].[dfp_con] 
	WHERE DS_CONTA = 'Receita de Venda de Bens e/ou Serviços' AND ORDEM_EXERC = 'ÚLTIMO'

),

--Buscando cadastro das empresas 
cad AS (
SELECT	
	DISTINCT 
	CNPJ_CIA, 
	SIT,DT_REG,
	SETOR_ATIV,
	TP_MERC,
	CONTROLE_ACIONARIO,
	UF,
	AUDITOR 
FROM [B3_DATA_DISCOVERING].[dbo].[dfp_cad]
),

OBT AS (
--Juntando as duas tabelas
SELECT 
	DRE.CNPJ_CIA,
	DRE.DENOM_CIA,
	DRE.DS_CONTA,
	DRE.VL_CONTA,
	CAD.SIT,DT_REG,
	CAD.SETOR_ATIV,
	CAD.TP_MERC,
	CAD.CONTROLE_ACIONARIO,
	CAD.UF,
	CAD.AUDITOR 
	   
FROM DRE
LEFT JOIN cad ON DRE.CNPJ_CIA = cad.CNPJ_CIA
)

SELECT 
DISTINCT
AUDITOR,
DS_CONTA,
UF,
DENOM_CIA,
VL_CONTA,
SUM(VL_CONTA) OVER (PARTITION BY AUDITOR) AS VALOR_CONTA_AUDITOR,
SUM(VL_CONTA) OVER (PARTITION BY UF) AS VALOR_CONTA_UF

FROM OBT
ORDER BY 4 DESC






